name: Fetch Upstream

on:
  schedule:
    - cron: '*/120 * * * *'
  workflow_dispatch:

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch Upstream
        uses: bdougie/fetch-upstream@master
        with:
          upstream: eclipse-dataspaceconnector/DataSpaceConnector
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
